Improve logging and error handling of tools/deploy

diff --git a/tools/deploy b/tools/deploy
--- a/tools/deploy
+++ b/tools/deploy
@@ -29,19 +29,31 @@ fi
 subtree_changed () {
     local dir=$1
     local range=$2
-    ! git diff --quiet "$range" -- "$dir"
+    if git diff --quiet "$range" -- "$dir"; then
+        return 1
+    else
+        # Exit codes greater than 1 are actual errors rather than an indication
+        # of a non-null diff.
+        if [ "$?" -gt 1 ]; then
+            exit 1
+        fi
+        return 0
+    fi
 }
 
 # Tag an image with the specified tag and push it to the Docker Hub.
 push_image () {
     local image=$1
     local tag=$2
+    echo >&2 "Tagging ${image}:latest as ${image}:${tag}..."
     docker tag "$image" "$image":"$tag"
+    echo >&2 "Pushing ${image} to Docker Hub..."
     docker push "$image"
 }
 
 # The DOCKER_* environment variables are secrets we need to have configured for
 # the Travis project.
+echo >&2 "Logging into Docker Hub..."
 docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 
 if subtree_changed checkrealtime/ "$TRAVIS_COMMIT_RANGE"; then
